#ifndef __FPGA_DEFINE_H
#define __FPGA_DEFINE_H



#define FPGA_BASE_ADDR ((uint32_t)0x60000000) 
#define ADDR_SHIFT(x) ((x)<<1)


#define _FPGA_REG_(x) *(volatile unsigned short*)(FPGA_BASE_ADDR + ADDR_SHIFT(x))

//UART
#define UART_TBASE (0<<7)
#define UART_RBASE (1<<7)

#define UART_BUFFER 0
#define UART_BAUDRATE 1
#define UART_CONFIG 2
#define UART_STATE 6

#define UART_NUMMBER(x) ((x)<<3)

#define _UART_TXBUFF_(x) _FPGA_REG_(UART_TBASE + UART_BUFFER + UART_NUMMBER(x))
#define _UART_TXBAUD_(x) _FPGA_REG_(UART_TBASE + UART_BAUDRATE + UART_NUMMBER(x))
#define _UART_TCONFIG_(x) _FPGA_REG_(UART_TBASE + UART_CONFIG + UART_NUMMBER(x))

#define _UART_RXBUFF_(x) _FPGA_REG_(UART_RBASE + UART_BUFFER + UART_NUMMBER(x))
#define _UART_RXBAUD_(x) _FPGA_REG_(UART_RBASE + UART_BAUDRATE + UART_NUMMBER(x))
#define _UART_RCONFIG_(x) _FPGA_REG_(UART_RBASE + UART_CONFIG + UART_NUMMBER(x))
#define _UART_RSTATE(x) _FPGA_REG_(UART_RBASE + UART_STATE + UART_NUMMBER(x))


#define UART_PARITY_NO		0x0000
#define UART_PARITY_ODD		0x000d
#define UART_PARITY_EVEN	0x0009
#define UART_STOPBIT_ONE	0x0000
#define UART_STOPBIT_TWO	0x0002

#define UART_ENABLE	    0x0001
#define UART_DISABLE	0x0000

#endif

